### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by danli349** [KrishnaswamyLab/PHATE#139]
Hello:

When I run `phate_operator.fit_transform`, there is an `AttributeError: 'NoneType' object has no attribute 'split'` error.
Could you please let me know how to fix it?
Thanks a lot

```
from anndata import AnnData
import scanpy.external as sce
import phate
import scprep

adata.X = scprep.normalize.library_size_normalize(adata.X)
adata.X = scprep.transform.sqrt(adata.X)
phate_operator = phate.PHATE(knn=5, gamma=0, decay=20, t=120)
tree_phate = phate_operator.fit_transform(adata.X)
```

```
Calculating PHATE...
  Running PHATE on 16813 observations and 27998 variables.
  Calculating graph and diffusion operator...
    Calculating PCA...
    Calculated PCA in 17.77 seconds.
    Calculating KNN search...
    Calculated KNN search in 24.04 seconds.
    Calculating affinities...
    Calculated affinities in 3.14 seconds.
  Calculated graph and diffusion operator in 44.98 seconds.
  Calculating landmark operator...
    Calculating SVD...
    Calculated SVD in 2.52 seconds.
    Calculating KMeans...
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f61261eeee0>
Traceback (most recent call last):
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f61261eeee0>
Traceback (most recent call last):
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7f61261eeee0>
Traceback (most recent call last):
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/home/dan/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
    Calculated KMeans in 4.88 seconds.
  Calculated landmark operator in 8.37 seconds.
  Calculating diffusion potential...
  Calculated diffusion potential in 1.03 seconds.
  Calculating metric MDS...
  Calculated metric MDS in 5.55 seconds.
Calculated PHATE in 59.93 seconds.
```

`phate.__version__` 
`'1.0.10'`

`threadpoolctl.__version__`
`'3.1.0'`

**Comment by scottgigante** [comment]
Looks like a) this is an issue with `threadpoolctl`; b) the exception is ignored (`Exception ignored on calling ctypes callback function:`); and c) PHATE is calculated correctly. I'd encourage you to open an issue with `threadpoolctl`.
