### ISSUE TITLE
Problems with phate.plot.rotate_scatter3d

### ISSUE THREAD

**Issue by ahof1704** [KrishnaswamyLab/PHATE#69]
Hi,

When trying to plot the 3D embedding giving by PHATE, I am running into an indexing problem. For the sake of reproducibility, here is an example using your example dataset:

```
import phate
tree_data, tree_clusters = phate.tree.gen_dla()
phate_operator = phate.PHATE(k=15, t=100)
tree_phate = phate_operator.fit_transform(tree_data)
phate.plot.rotate_scatter3d(tree_phate, c=tree_clusters) #BTW, I think this line is wrong on your example... the original shows _**phate.plot.rotate_scatter3d(phate_operator, c=tree_clusters)**_
```
Result:
phate.plot.rotate_scatter3d(tree_phate, c=tree_clusters)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Documents/PHATE/Python/phate/plot.py", line 549, in rotate_scatter3d
    **kwargs)
  File "</home/.conda/envs/antonio_phate/lib/python3.7/site-packages/decorator.py:decorator-gen-18>", line 2, in rotate_scatter3d
  File "/home/.conda/envs/antonio_phate/lib/python3.7/site-packages/scprep/utils.py", line 78, in _with_pkg
    return fun(*args, **kwargs)
  File "/home/.conda/envs/antonio_phate/lib/python3.7/site-packages/scprep/plot/scatter.py", line 1024, in rotate_scatter3d
    scatter3d(data, ax=ax, **kwargs)
  File "</home/.conda/envs/antonio_phate/lib/python3.7/site-packages/decorator.py:decorator-gen-17>", line 2, in scatter3d
  File "/home/.conda/envs/antonio_phate/lib/python3.7/site-packages/scprep/utils.py", line 78, in _with_pkg
    return fun(*args, **kwargs)
  File "/home/.conda/envs/antonio_phate/lib/python3.7/site-packages/scprep/plot/scatter.py", line 915, in scatter3d
    z=select.select_cols(data, idx=2),
  File "/home/.conda/envs/antonio_phate/lib/python3.7/site-packages/scprep/select.py", line 363, in select_cols
    data = data[:, idx]
IndexError: index 2 is out of bounds for axis 1 with size 2

Any ideas about what is going wrong here? 
Please, let me know if you need any further details.

Thanks

**Comment by ahof1704** [comment]
I am closing it since it is not really an issue, but here is some further clarification:
- The script given as an example here https://github.com/KrishnaswamyLab/PHATE/tree/master/Python did not work (likely because of the issue with the argument pointed above).
- The example from the documentation works fine: https://phate.readthedocs.io/en/stable/api.html#module-phate.plot

So I guess it is just a matter of updating the example given in Github.

Sorry about that!

**Comment by scottgigante** [comment]
I'm reopening this as two separate issues:
1. The example here should set `n_components=3`
2. `scprep.plot.rotate_scatter3d` should give a better error message when data passed is less than 3D.
